name: Publish to Github Package
on:
  push: 
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Nodejs and Npm auth
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@rofixwork"
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        if: success()
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}